### ISSUE TITLE
Support for rational numbers

### ISSUE THREAD

**Issue by idoric** [PabloRuizCuevas/numty#1]
Is support for rational numbers part of the project goals? In other words, is it envisaged to be able to perform calculations on fractions, and to be able to obtain exact results in the form of simplified fractions? (For example 4/3×1.3^3 = 2197/750)

**Comment by PabloRuizCuevas** [comment]
Is not a  priority, but is not discarded.

Doing this will mean to support other data types of arrays, like complex number, strings or rationals, if doing so, rational numbers could be one additional type.

The real question here is how to do it... typst does´t have a well established way of doing classes/ objects, though they can be reproduced by using dictionaries with a type attribute.

I want this library to work with simple list if possible and I also don´t want to make excessive datatype checking (not checking all items in the arrays) ... 

Maybe one way is letting numeric list as default and the rest specified by a dictionary using a new function called

nt.array( my-list, type: 'rational')  or 'complex' or 'string' 

Then we could check the type in the operations and put custom operations for custom data types...

Still deciding this, if you have ideas let me know. In any case I'm slightly conflicted with rationals as they are not native in numpy which is the reference library for numty. But we could still do a plugin-like system like cetz does with the plots etc.

**Comment by PabloRuizCuevas** [comment]
Closing it for now, if there is a lot of interest I will open it back.
